# /etc/usbrelayd.cfg 
[MQTT]
# Hostname or IP address of your MQTT Broker
BROKER = mqtt
# Name your client connects as
CLIENTNAME = MyUSBRelay
TLS = 
USER = 
PASS = 
PORT = 1883
TOPIC = 

[HOMEASSISTANT]
# Set this to get usbrelayd to publish the relays with HomeAssistant's
# discovery protocol.
# The default value for HA is "homeassistant"
TOPIC =
