.TH USBRELAYD 8
.SH NAME
usbrelayd \- MQTT client for controlling USB HID relay devices
.SH SYNOPSIS
.B usbrelayd
.SH DESCRIPTION

usbrelayd is a daemon that allows controlling locally connected USB
HID relays remotely via MQTT protocol.

.SH FILES
.TP
/etc/usbrelayd.conf
Configuration file.


.SH "SEE ALSO"
.BR usbrelay(1)
.SH AUTHOR
This man page was written by Michal Sojka <wsh@2x.cz> for Debian
